<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="manjunathspc" ignored="0" name="Checking Admin flow" tests="1" failures="1" timestamp="20 Jan 2020 12:17:16 GMT" time="27.752" errors="0">
  <testcase name="@AfterMethod closebrowser" time="1.043" classname="base.SuperTestNG">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at base.SuperTestNG.closebrowser(SuperTestNG.java:182)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod closebrowser -->
  <testcase name="SuperAdminflow" time="4.022" classname="WH.AdminLogin">
    <failure type="java.lang.AssertionError" message="expected [https://india.unicityportal.com/test_warehouseorder/warehouseorders] but found [https://india.unicityportal.com/test_warehouseorder/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://india.unicityportal.com/test_warehouseorder/warehouseorders] but found [https://india.unicityportal.com/test_warehouseorder/auth/login]
at pages.Landingpage.AdminLogin(Landingpage.java:29)
at WH.AdminLogin.SuperAdminflow(AdminLogin.java:68)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- SuperAdminflow -->
</testsuite> <!-- Checking Admin flow -->
